### ISSUE TITLE
error in runtime 

### ISSUE THREAD

**Issue by kerolos** [farisalasmary/deepspeech2-online-decoder#2]
**when i run this python script (python website_server.py) i got the following state:**

/deepspeech2-online-decoder# python3 website_server.py 
 * Serving Flask app "website_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:9999/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 755-754-811

**the the bash script i got this error :**

/deepspeech2-online-decoder# ./run_decoder_server.sh 
Traceback (most recent call last):
  File "decoder_server.py", line 6, in <module>
    from data.extended_data_loader import OnlineSpectrogramParser
  File "/workspace/deepspeech.pytorch/deepspeech2-online-decoder/data/extended_data_loader.py", line 17, in <module>
    from .spec_augment import spec_augment
ModuleNotFoundError: No module named 'data.spec_augment'
./run_decoder_server.sh: line 7: --cuda: command not found

i am using a docker for training model and streaming

**Comment by farisalasmary** [comment]
You are most probably using the latest version of Deepspeech2 implementation which has been changed a lot!

I forked the project and started building my own version. 
You can find it here:
https://github.com/farisalasmary/deepspeech.pytorch
