### ISSUE TITLE
how we can stream the model in python

### ISSUE THREAD

**Issue by kerolos** [farisalasmary/deepspeech2-online-decoder#3]
is it possible to run the model online in python using only CPU ?

i found a a good python script to run it in python, but the model run in this script using jit (PyTorch- lightning)
https://github.com/LearnedVector/A-Hackers-AI-Voice-Assistant/blob/master/VoiceAssistant/speechrecognition/engine.py

is it hard to extent your code to stream the model in python?

**Comment by farisalasmary** [comment]
If I got your point, I think you want to run the model on the CPU. If this is what you want, you can simply modify the file:
`run_decoder_server.sh`
and remove the argument `--cuda`
