### ISSUE TITLE
Please specify commit of SeanNaren / deepspeech.pytorch

### ISSUE THREAD

**Issue by naveenss1995** [farisalasmary/deepspeech2-online-decoder#4]
this repo seems to be built on an older commit of SeanNaren deepspeech.pytorch as in the new commit they have moved to hydra configs rather than opt file. also there seems to be compatibily issues with audio config obtaind from latest librispeech model. It would help a lot if you can mention the commit on which this repo is created.

**Comment by farisalasmary** [comment]
I forked the original repo and I'm currently building on top of it. 
Here is my forked repo:
https://github.com/farisalasmary/deepspeech.pytorch

**Comment by naveenss1995** [comment]
Thanks a lot , this helps

**Comment by farisalasmary** [comment]
You're welcome!
